<?php 
$title =  $film->getTitle();
$cssLink = '../css/show-style.css';

ob_start();
?>
<main>
    <div class="<?= (isset($_GET['success'])) ? 'success' : 'hide' ?> ">
        <p>Vos modification sont enregistrées avec succès</p>     
    </div>
    <div class="section-wrap">
        <section class="show-section">
            <div class="movie-card">
                <div class="img-film">
                    <?php if ($film->getPoster_path()) { ?>
                        <img src="https://image.tmdb.org/t/p/w1280<?= $film->getPoster_path() ?>" alt="Poster film">
                    <?php } else { ?>
                        <div class="empty-path"><span >🎥</span></div>
                    <?php } ?>            
                </div>
                <div class="movie-details">
                    <div >
                        <div class="top-right-side"> 
                            <div><h1> <?= htmlspecialchars($film->getTitle()) ?></h1></div>
                            <div class="top-right-side-link"><a href="">➕</a></div>
                        </div>
                        <div class="bottom-right-side">
                            <p>📆<?= substr(htmlspecialchars($film->getRelease_date()),0,4 )?>&nbsp;|&nbsp;</p>
                            <p>⏱ <?= $film->getRuntime() ?> min | &nbsp;</p>
                            <p> 🎭
                                <?php $num = 0 ?>
                                <?php foreach ($film->getGenres() as $genre) { ?>
                                    <?php $num++ ?>
                                    <?= ($num < count($film->getGenres())) ? $genre.', ' : $genre ?>
                                <?php } ?> 

                            </p>
                        </div>
                        <div class="bottom-right-side">
                            <p> ⭐ <?= number_format($film->getVote_average(), 1).'/10 ('. number_format($film->getVote_count(),0,',',' ') . ' votes)' ?> </p>
                        </div>

                    </div>
                </div>
            </div>

            <div class="synopsis">
                <p><?= htmlspecialchars($film->getOverview()) ?></p>
            </div>
        </section>
        <section>
            <div class="categories-list">
                <ul>
                    <li><button type='button'  onclick="history.back()">Retour à la page précédente</button></li>
                </ul>
            </div>
        </section>
    </div>
    
</main>


<?php
$content = ob_get_clean();
require(__DIR__.'/../base.phtml');
?>