<header>
    <h1>🎬 CinéStream + </h1>
    <p>votre cinéma, partout, à tout moment.</p>

    <div class="nav-container">
        
        <button class="hamburger" id="hamburger"> ☰</button>
        <nav id="nav-menu">
            <ul>
                <li><a href="?route=index"> </span> 🎞️ <span> VIDÉOTHÈQUE </a></li>
                <li><a href="?route=search"> <span> 🔍 </span> RECHERCHE </a></li>
            </ul>
        </nav>

    </div>

</header>

<script>
    const hamburger = document.getElementById("hamburger");
    const navMenu = document.getElementById("nav-menu");

    hamburger.addEventListener("click", () => {
        navMenu.classList.toggle("active");
    });
</script>