<?php 
$title = 'CinéStream +' ;
$cssLink = '../css/index-style.css';

ob_start();
?>
<main>
    <section class="movie-section">
        <div class="categories-list">
            <form action="?route=sort" method="post">
                <ul>
                    <li><button type='submit' name="all" value="all">Tous les films</button></li>
                    <?php foreach ($genres as $genre) { ?>
                    <li><button type="submit" name="genre" value="<?= $genre->getId() ?>"><?= htmlspecialchars($genre->getName()) ?></button></li>
                    <?php } ?>
                    <li><button type='submit' name="genre" value="">n/c</button></li>
                    <li><button type='submit' name="sort" value="1">👁️</button></li>
                    <li><button type='submit' name="sort" value="0">🕐</button></li>
                </ul>
            </form>
            
        </div>
        <?php if (isset($films)) {?>        
        <div class="movies-card">
            <?php foreach ($films as $film) {?>
            <div class="movie-card">
                <div class="poster-img">
                    <?php if ($film->getPoster_path()) { ?>
                    <img src="https://image.tmdb.org/t/p/w1280<?= $film->getPoster_path() ?>" alt="Poster film">
                    <?php } else { ?>
                    <div class="empty-path"><span >🎥</span></div>
                    <?php } ?>
                </div>
                <div class="down-card">
                    <h3><?= htmlspecialchars($film->getTitle()) ?></h3>
                    <div class="bottom-card">
                        <div class="span1"><span>📆 <?= $film->getRelease_date() ?></span></div>
                        <div class="span2"><span><?= ($film->getIsWatched())? '👁️' : '🕐' ?> <span></div>
                    </div>

                </div>
            </div>
            <?php } ?>
        </div>
        <?php }else {?>
        <div class="invitation">
            <p class="invitation-emoji">🚫</p>
            <p> Votre vidéothèque est vide!, veuillez rajouter des films</p>
        </div>
        <?php } ?>
    </section>
</main>
<?php
$content = ob_get_clean();
require('base.phtml');
?>