<?php 
$title =  $film->getTitle();
$cssLink = '../css/show-style.css';

ob_start();
?>
<main>
    <div class="<?= (isset($_GET['success'])) ? 'success' : 'hide' ?> ">
        <p>Vos modification sont enregistrées avec succès</p>     
    </div>
    <div class="section-wrap">
        <section class="show-section">
            <div class="movie-card">
                <div class="img-film">
                    <?php if ($film->getPoster_path()) { ?>
                    <img src="https://image.tmdb.org/t/p/w1280<?= $film->getPoster_path() ?>" alt="Poster film">
                    <?php } else { ?>
                    <div class="empty-path"><span >🎥</span></div>
                    <?php } ?>            
                </div>
                <div class="movie-details">
                    <div >
                        <div class="top-right-side"> 
                            <h1> <?= htmlspecialchars($film->getTitle()) ?></h1>
                            <div class="top-right-side-link"><a href="?route=update&id=<?= $film->getId() ?>&genreId=<?= $film->getGenre_id() ?>">✏️</a> <a href="?route=delete&id=<?= $film->getId() ?>" onclick=" return deleteConfirmation()">❌</a></div>
                        </div>
                        <div class="bottom-right-side">
                            <p>📆 <?= $film->getRelease_date() ?> | &nbsp;</p>
                            <p> ⏱ <?= $film->getRuntime() ?> min | &nbsp;</p>
                            <p> 🎭 <?= $genreShow  ?> |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
                            <p> <span><?= ($film->getIsWatched())? '👁️' : '🕐' ?></p>
                        </div>

                    </div>
                    <div class="comment">
                        <p> <?= $film->getDescription() ?></p>
                    </div>
                </div>
            </div>

            <div class="synopsis">
                <p><?= htmlspecialchars($film->getOverview()) ?></p>
            </div>
        </section>
    </div>
    
</main>

<script>
    function deleteConfirmation() {
        return confirm('Etes-vous sûr de vouloir supprimer ce filme ?');
    }
</script>

<?php
$content = ob_get_clean();
require('base.phtml');
?>